export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const QUANTITY = "INC_QUANTITY";